import type { Article } from './types'

// Sample content. Every game, studio and person below is fictional.
export const articles: Article[] = [
  {
    id: 'a-001',
    slug: 'lantern-night-interview',
    kind: 'cover-story',
    title: '一個人、三年、兩千盞燈：《燈籠夜行》的夜市是怎麼點亮的',
    dek: '成員 @阿燈 把老家巷口的夜市做成橫向卷軸。我們聊了光、攤販的聲音，還有第 47 版 Demo。',
    coverWord: '夜行',
    author: { name: '小鹿', handle: '@deer' },
    publishedAt: '2026-10-03',
    readMinutes: 9,
    cover: { scene: 'nightMarket', alt: '《燈籠夜行》畫面：夜市街道上掛滿燈籠，主角提著一盞燈走過攤位' },
    body: [
      { type: 'p', text: '週五晚上十一點，Discord 語音頻道裡有六個人同時在跑同一個 Demo。畫面是一條窄窄的夜市，燈籠從畫面上緣垂下來，主角提著一盞小燈往右走。有人說：「第三個攤位的燈太亮了，我以為那是可以互動的。」@阿燈 回：「好，記下來。」這是《燈籠夜行》第 47 次公開測試。' },
      { type: 'h2', text: '從巷口開始' },
      { type: 'p', text: '「我小時候住的地方，巷口每週二、四有夜市。收攤之後整條街會一瞬間變暗，只剩幾盞還沒拆的燈。」@阿燈 說，整個遊戲就是從那個畫面長出來的：玩家的任務不是打敗誰，而是在夜市收攤前，把該點的燈點起來。' },
      { type: 'p', text: '遊戲沒有血條。燈籠的亮度就是生命值，也是地圖。燈越少，畫面越暗，攤販的聲音也會慢慢聽不見。' },
      { type: 'quote', text: '我想做一個「暗下來」會讓人難過，而不是讓人害怕的遊戲。', by: '@阿燈' },
      { type: 'figure', cover: { scene: 'nightMarket', alt: '夜市街道的另一段，燈籠較少、畫面較暗' }, caption: '第 3 關後半段。燈籠數量從 40 盞降到 12 盞，攤販音效同步淡出。（示範畫面）' },
      { type: 'h2', text: '兩千盞燈的預算' },
      { type: 'p', text: '全遊戲一共有兩千零四十盞燈，每一盞都是手擺的。@阿燈 用試算表管理它們：位置、顏色、會不會被風吹熄。「測試夜的回饋幾乎都跟燈有關，」他笑，「大家比我還在意哪盞燈歪了。」' },
      { type: 'p', text: '社群的測試回饋直接改變了關卡設計。第 30 版之前，燈熄掉之後就不能再點；在連續三次測試都有人卡關之後，改成可以用攤販給的火柴重新點燃。這個改動讓通關率從四成出頭拉到將近八成。' },
      { type: 'h2', text: '下一步' },
      { type: 'p', text: 'Demo 目前在 itch.io 可以免費下載，完整版預計明年春天上架。@阿燈 說，在那之前，每個月的第一個週五還是會開測試夜。「你們繼續錄，我繼續改。」' },
    ],
  },
  {
    id: 'a-002',
    slug: 'last-train-review',
    kind: 'review',
    title: '《最後一班捷運》試玩：最可怕的，是它太像通勤',
    dek: '二十分鐘、一節車廂、一個不肯下車的乘客。四位成員的交叉評測。',
    author: { name: '夜貓', handle: '@owl' },
    publishedAt: '2026-10-01',
    readMinutes: 6,
    cover: { scene: 'subway', alt: '《最後一班捷運》畫面：深夜空蕩的捷運車廂，盡頭站著一個人影' },
    body: [
      { type: 'p', text: '《最後一班捷運》是成員 @月台 用兩個週末做完的短篇恐怖遊戲。玩法很單純：你在末班車上，要在二十分鐘內決定哪一站下車。車廂盡頭有一個人，每過一站，他就離你近一點。' },
      { type: 'p', text: '它不靠突然跳出來的東西嚇人。真正讓人坐立難安的，是那些太真實的細節：到站廣播的語氣、車窗外一閃而過的月台廣告、手機電量顯示 12%。' },
      { type: 'review', reviewers: [
        { handle: '@owl', score: 8, line: '音效設計是全場最佳，廣播聲一響我就想下車。' },
        { handle: '@deer', score: 7, line: '二十分鐘剛好，但第二輪的變化不夠多。' },
        { handle: '@pixelkid', score: 9, line: '兩個週末做成這樣，完成度讓人嫉妒。' },
        { handle: '@tofu', score: 6, line: '我太常搭末班車了，玩完不太敢回家。' },
      ] },
      { type: 'h2', text: '該不該玩' },
      { type: 'p', text: '如果你喜歡不靠血腥、靠氣氛的恐怖遊戲，這是這個月最值得花二十分鐘的東西。建議戴耳機，燈不要全關。' },
    ],
  },
  {
    id: 'a-003',
    slug: 'reading-playtest-feedback',
    kind: 'column',
    title: '第一次發 Demo？十條試玩回饋，這樣讀',
    dek: '「好玩」和「不好玩」都不是回饋。把測試夜聽到的話翻譯成可以改的東西。',
    author: { name: '豆腐', handle: '@tofu' },
    publishedAt: '2026-09-26',
    readMinutes: 7,
    cover: { scene: 'desk', alt: '深夜書桌上的螢幕顯示著遊戲測試畫面' },
    body: [
      { type: 'p', text: '發 Demo 最痛苦的不是被罵，是收到一堆你不知道該怎麼改的話。這篇整理了測試夜裡最常出現的十種回饋，以及它們背後通常在說什麼。' },
      { type: 'h2', text: '「我不知道要幹嘛」' },
      { type: 'p', text: '這幾乎從來不是教學不夠長，而是第一個目標不夠近。試著讓玩家在三十秒內完成一件小事，再告訴他下一件。' },
      { type: 'h2', text: '「手感怪怪的」' },
      { type: 'p', text: '先問對方用鍵盤還是手把，再請他錄一段。十次有八次，問題出在起跳前的那幾個影格，或是落地後不能立刻動作。' },
      { type: 'quote', text: '把回饋當症狀，不要當處方。玩家很會發現問題，但不一定會開藥。' },
      { type: 'p', text: '剩下的八條，我們放在 Discord 的 #開發者頻道 置頂，歡迎補充你自己被罵過、但後來發現很有用的那一句。' },
    ],
  },
  {
    id: 'a-004',
    slug: 'roguelike-thirty-seconds',
    kind: 'feature',
    title: 'Roguelike 的三十秒法則：為什麼你「再一局」停不下來',
    dek: '從死亡到重新開始之間的那段時間，決定了一款 roguelike 的命。',
    author: { name: '像素小孩', handle: '@pixelkid' },
    publishedAt: '2026-09-20',
    readMinutes: 11,
    cover: { scene: 'cards', alt: '牌組構築遊戲畫面：五張手牌展開在桌上，對面是一個大型敵人' },
    body: [
      { type: 'p', text: '我們拆了社群成員這一年做的七款 roguelike Demo，計算從角色死亡到下一局可以操作之間的秒數。結果很明顯：留存最好的三款，都在三十秒以內。' },
      { type: 'h2', text: '死亡畫面是一種邀請' },
      { type: 'p', text: '好的死亡畫面不是懲罰，是一句「再來一次？」。把結算、解鎖、重新開始壓在同一個畫面，讓玩家的手不用離開按鍵。' },
      { type: 'p', text: '這不代表要把所有東西都砍掉。重點是讓每一個停頓都有東西可看：剛解鎖的卡、下一局的種子、上一局的死因。' },
    ],
  },
  {
    id: 'a-005',
    slug: 'typhoon-day-games',
    kind: 'feature',
    title: '颱風假玩什麼：編輯部推薦的八款「窗外很吵」遊戲',
    dek: '雨打在窗上的時候，最適合種田、蓋房子，或是什麼都不做。',
    author: { name: '小鹿', handle: '@deer' },
    publishedAt: '2026-09-14',
    readMinutes: 5,
    cover: { scene: 'farm', alt: '風雨中的小農場，菜園和小屋，樹被風吹彎' },
    body: [
      { type: 'p', text: '放颱風假的那天，Discord 的上線人數會一口氣變成平常的兩倍。我們在 #閒聊 問大家在玩什麼，整理出這份清單：節奏慢、可以隨時暫停、而且聽得見雨聲也不會出戲。' },
      { type: 'p', text: '清單上有三款是成員自己做的，其中《小雨田》的作者說，遊戲裡的雨聲就是去年颱風天在陽台錄的。' },
    ],
  },
]
