import type { Work } from './types'

// Sample content. Every work and creator is fictional; links point at example.com.
export const works: Work[] = [
  {
    id: 'w-001',
    slug: 'lantern-night',
    kind: 'game',
    title: '燈籠夜行',
    subtitle: 'Lantern Night',
    creator: { name: '阿燈', handle: '@阿燈' },
    blurb: '在夜市收攤之前，把該點的燈點起來。',
    description: [
      '橫向卷軸冒險。燈籠的亮度就是生命值，也是地圖：燈越少，畫面越暗，攤販的聲音也會慢慢聽不見。',
      '目前 Demo 收錄三關，約 40 分鐘。支援鍵盤與手把。',
    ],
    tags: ['橫向卷軸', '單人', '約 40 分鐘'],
    cover: { scene: 'nightMarket', alt: '《燈籠夜行》：夜市街道與燈籠' },
    links: [{ label: 'itch.io', url: 'https://example.com/lantern-night' }],
    publishedAt: '2026-10-02',
    meta: 'Demo 0.47',
    status: 'new',
  },
  {
    id: 'w-002',
    slug: 'last-train-stream',
    kind: 'video',
    title: '最後一班捷運・開發直播',
    subtitle: 'Last Train devlog',
    creator: { name: '月台', handle: '@月台' },
    blurb: '今晚加第二條路線，邊做邊聊。',
    description: [
      '每週六晚上的開發直播。這一集要加入從中途站下車的新結局，也會回應測試夜收到的回饋。',
    ],
    tags: ['開發直播', '恐怖', '短篇'],
    cover: { scene: 'subway', alt: '深夜捷運車廂內部' },
    links: [{ label: '直播頻道', url: 'https://example.com/last-train-live' }],
    publishedAt: '2026-10-04',
    meta: 'LIVE',
    status: 'live',
  },
  {
    id: 'w-003',
    slug: 'jiufen-map',
    kind: 'mod',
    title: '九份',
    subtitle: 'Jiufen map v2',
    creator: { name: '山城', handle: '@山城' },
    blurb: '沿著老街階梯往上爬，下雨天會多一條捷徑。',
    description: [
      '以山城老街為藍本的開放地圖 MOD。第二版加入夜間光照與雨天限定路線。',
      '安裝說明與相容版本請見下載頁。',
    ],
    tags: ['地圖', '探索', '雨天限定'],
    cover: { scene: 'hillTown', alt: '山坡上層層疊疊的房子與紅燈籠，遠方是海' },
    links: [{ label: '下載頁', url: 'https://example.com/jiufen-map' }],
    publishedAt: '2026-09-27',
    meta: 'v2.0',
  },
  {
    id: 'w-004',
    slug: 'kaiten-defense',
    kind: 'game',
    title: '迴轉壽司防衛戰',
    subtitle: 'Kaiten Defense',
    creator: { name: '鮭魚', handle: '@鮭魚' },
    blurb: '輸送帶上的每一盤都要守住。',
    description: [
      '塔防小品。敵人沿著迴轉壽司的輸送帶前進，你要用醬油、芥末與茶杯擋下牠們。',
    ],
    tags: ['塔防', '休閒', '15 分鐘一局'],
    cover: { scene: 'sushi', alt: '俯視的迴轉壽司輸送帶，盤子上有各色壽司' },
    links: [
      { label: 'itch.io', url: 'https://example.com/kaiten-defense' },
      { label: '網頁版', url: 'https://example.com/kaiten-defense/play' },
    ],
    publishedAt: '2026-09-18',
    meta: 'v1.2',
    featured: true,
  },
  {
    id: 'w-005',
    slug: 'speedrun-1247',
    kind: 'video',
    title: '12:47 全破紀錄',
    subtitle: 'Any% speedrun',
    creator: { name: '跳跳', handle: '@hop' },
    blurb: '第四關那個牆跳，練了兩百次。',
    description: [
      '在自製平台遊戲《方塊山》的 Any% 速通紀錄，附逐段解說字幕。',
    ],
    tags: ['速通', '解說'],
    cover: { scene: 'platformer', alt: '平台遊戲畫面：角色在方塊之間跳躍' },
    links: [{ label: '觀看影片', url: 'https://example.com/speedrun-1247' }],
    publishedAt: '2026-09-24',
    meta: '18:32',
  },
  {
    id: 'w-006',
    slug: 'dusk-knight',
    kind: 'art',
    title: '黃昏騎士',
    subtitle: 'Fan pixel art',
    creator: { name: '墨', handle: '@sumi' },
    blurb: '64×64 像素，花了一整個颱風假。',
    description: [
      '以社群 Game Jam 作品角色為主題的像素同人。原始檔為 64×64，放大 8 倍輸出。',
    ],
    tags: ['像素', '同人'],
    cover: { scene: 'portrait', alt: '夕陽前披著斗篷的像素騎士' },
    links: [{ label: '作品頁', url: 'https://example.com/dusk-knight' }],
    publishedAt: '2026-09-21',
    meta: '64×64',
  },
  {
    id: 'w-007',
    slug: 'box-garden-levels',
    kind: 'mod',
    title: '推箱花園 30 關',
    subtitle: 'Level pack',
    creator: { name: '豆腐', handle: '@tofu' },
    blurb: '每一關都只差一步，就是差那一步。',
    description: [
      '推箱子類解謎的自製關卡包，難度從第 1 關緩慢爬升到第 30 關，附官方解法影片。',
    ],
    tags: ['關卡包', '解謎'],
    cover: { scene: 'puzzle', alt: '推箱子解謎關卡的俯視畫面' },
    links: [{ label: '下載關卡', url: 'https://example.com/box-garden' }],
    publishedAt: '2026-09-15',
    meta: '30 關',
  },
  {
    id: 'w-008',
    slug: 'little-rain-field',
    kind: 'game',
    title: '小雨田',
    subtitle: 'Little Rain Field',
    creator: { name: '禾', handle: '@he' },
    blurb: '颱風天的菜園，雨聲是在陽台錄的。',
    description: [
      '慢節奏的種田遊戲，天氣會影響每一塊田。沒有時間限制，隨時可以存檔離開。',
    ],
    tags: ['種田', '放鬆'],
    cover: { scene: 'farm', alt: '雨中的小農場' },
    links: [{ label: 'itch.io', url: 'https://example.com/little-rain-field' }],
    publishedAt: '2026-09-12',
    meta: 'Demo',
  },
]
